version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: epitrello_db
    environment:
      POSTGRES_USER: epitrello
      POSTGRES_PASSWORD: epitrello_password
      POSTGRES_DB: epitrello
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: epitrello_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: epitrello_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
