name: CI

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  REPO_NAME: 'EpitechPGE3-2025/G-PRO-500-NAN-5-1-professionalwork-5'

jobs:
  check_if_mirror:
    runs-on: ubuntu-latest
    if: github.repository != '{{ env.REPO_NAME }}'
    steps:
      - name: "Validate"
        run: echo "This is not the main repository. Proceeding with mirroring."

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Lint backend
        run: npm run lint --if-present
        working-directory: backend

      - name: Test backend
        run: npm test --if-present
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint --if-present
        working-directory: frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: frontend

  push_to_mirror:
    needs: [check_if_mirror, backend, frontend]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Mirroring"
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:${{ env.REPO_NAME }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
